eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9898/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
